services:
  webapp:
    hostname: webapp
    container_name: webapp
    image: dart:stable
    restart: always
    ports:
      - "8085:8085"
      - "8181:8181"
    build:
      context: .
    volumes:
      - ./lib/:/www/lib/
      - ./public/:/www/public/
  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: PasswordMongoDB
    ports:
      - "27018:27017"
    volumes:
      - ${PWD-.}/mongodb:/data/db